from contextlib import AbstractAsyncContextManager
from typing import Any

class SQSClient:
    async def send_message(self, **kwargs: object) -> dict[str, Any]: ...
    async def receive_message(self, **kwargs: object) -> dict[str, Any]: ...
    async def delete_message(self, **kwargs: object) -> dict[str, Any]: ...

class _ClientContext(AbstractAsyncContextManager[SQSClient]):
    async def __aenter__(self) -> SQSClient: ...
    async def __aexit__(self, exc_type: object, exc: object, tb: object) -> bool | None: ...

class Session:
    def client(self, service_name: str, **kwargs: object) -> _ClientContext: ...
