from collections.abc import Iterator, Mapping
from contextlib import AbstractAsyncContextManager
from typing import Any

class PostgresError(Exception): ...

class Record(Mapping[str, Any]):
    def __getitem__(self, key: str, /) -> Any: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...

class TransactionContext(AbstractAsyncContextManager[None]):
    async def __aenter__(self) -> None: ...
    async def __aexit__(self, exc_type: object, exc: object, tb: object) -> bool | None: ...

class Connection:
    async def execute(self, query: str, *args: object) -> str: ...
    async def executemany(self, query: str, args: object) -> None: ...
    async def fetch(self, query: str, *args: object) -> list[Record]: ...
    async def fetchrow(self, query: str, *args: object) -> Record | None: ...
    def transaction(self) -> TransactionContext: ...
    async def close(self) -> None: ...

class PoolAcquireContext(AbstractAsyncContextManager[Connection]):
    async def __aenter__(self) -> Connection: ...
    async def __aexit__(self, exc_type: object, exc: object, tb: object) -> bool | None: ...

class Pool:
    def acquire(self) -> PoolAcquireContext: ...
    async def close(self) -> None: ...

async def create_pool(
    *,
    dsn: str,
    min_size: int = ...,
    max_size: int = ...,
    **kwargs: object,
) -> Pool: ...
async def connect(dsn: str, **kwargs: object) -> Connection: ...
