from typing import Protocol

class Locator(Protocol):
    async def count(self) -> int: ...
    async def click(self) -> None: ...

class Page(Protocol):
    url: str

    def locator(self, selector: str) -> Locator: ...
    async def goto(self, url: str, *, wait_until: str) -> None: ...
    async def fill(self, selector: str, value: str) -> None: ...
    async def wait_for_load_state(self, state: str) -> None: ...
    async def screenshot(self, *, path: str, full_page: bool) -> None: ...

class Browser(Protocol):
    async def new_page(self, *, viewport: dict[str, int]) -> Page: ...
    async def close(self) -> None: ...

class Chromium(Protocol):
    async def launch(self) -> Browser: ...

class Playwright(Protocol):
    chromium: Chromium

class AsyncPlaywrightContextManager(Protocol):
    async def __aenter__(self) -> Playwright: ...
    async def __aexit__(self, exc_type: object, exc: BaseException | None, tb: object) -> None: ...

def async_playwright() -> AsyncPlaywrightContextManager: ...
